[2024-02-09T14:44:17.078+0000] {processor.py:153} INFO - Started process (PID=89) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:44:17.086+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:44:17.088+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:44:17.088+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:44:17.158+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:44:17.159+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:44:17.176+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:44:17.163+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:44:17.179+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:44:17.216+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.147 seconds
[2024-02-09T14:44:47.633+0000] {processor.py:153} INFO - Started process (PID=117) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:44:47.644+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:44:47.646+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:44:47.645+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:44:47.671+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:44:47.680+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:44:47.686+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:44:47.681+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:44:47.688+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:44:47.742+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.115 seconds
[2024-02-09T14:45:17.986+0000] {processor.py:153} INFO - Started process (PID=145) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:45:17.987+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:45:17.989+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:45:17.989+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:45:18.013+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:45:18.013+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:45:18.019+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:45:18.015+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:45:18.021+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:45:18.051+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.073 seconds
[2024-02-09T14:45:48.555+0000] {processor.py:153} INFO - Started process (PID=174) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:45:48.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:45:48.558+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:45:48.557+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:45:48.578+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:45:48.579+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:45:48.584+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:45:48.580+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:45:48.586+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:45:48.612+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.062 seconds
[2024-02-09T14:46:18.744+0000] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:46:18.745+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:46:18.746+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:46:18.746+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:46:18.773+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:46:18.773+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:46:18.780+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:46:18.776+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:46:18.781+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:46:18.813+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.074 seconds
[2024-02-09T14:46:49.357+0000] {processor.py:153} INFO - Started process (PID=232) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:46:49.358+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:46:49.360+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:46:49.360+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:46:49.384+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:46:49.385+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:46:49.391+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:46:49.386+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:46:49.393+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:46:49.429+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.077 seconds
[2024-02-09T14:47:19.728+0000] {processor.py:153} INFO - Started process (PID=261) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:47:19.730+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:47:19.731+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:47:19.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:47:19.750+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:47:19.751+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:47:19.757+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:47:19.753+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:47:19.758+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:47:19.791+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.069 seconds
[2024-02-09T14:47:50.361+0000] {processor.py:153} INFO - Started process (PID=290) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:47:50.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:47:50.364+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:47:50.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:47:50.401+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:47:50.402+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:47:50.408+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:47:50.403+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:47:50.409+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:47:50.440+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.092 seconds
[2024-02-09T14:48:21.248+0000] {processor.py:153} INFO - Started process (PID=320) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:48:21.250+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:48:21.253+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:48:21.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:48:21.277+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:48:21.278+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:48:21.298+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:48:21.283+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:48:21.330+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:48:21.370+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.129 seconds
[2024-02-09T14:48:51.788+0000] {processor.py:153} INFO - Started process (PID=349) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:48:51.790+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:48:51.792+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:48:51.792+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:48:51.819+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:48:51.820+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:48:51.827+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:48:51.822+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:48:51.829+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:48:51.870+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.124 seconds
[2024-02-09T14:49:22.649+0000] {processor.py:153} INFO - Started process (PID=387) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:49:22.653+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:49:22.655+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:49:22.655+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:49:22.680+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:49:22.682+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:49:22.689+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:49:22.684+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:49:22.691+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:49:22.725+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.082 seconds
[2024-02-09T14:49:53.182+0000] {processor.py:153} INFO - Started process (PID=416) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:49:53.183+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:49:53.185+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:49:53.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:49:53.282+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:49:53.289+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:49:53.309+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:49:53.297+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:49:53.326+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:49:53.406+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.229 seconds
[2024-02-09T14:50:23.666+0000] {processor.py:153} INFO - Started process (PID=445) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:50:23.667+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:50:23.669+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:50:23.669+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:50:23.696+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:50:23.697+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:50:23.704+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:50:23.699+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:50:23.705+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:50:23.736+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.078 seconds
[2024-02-09T14:50:54.101+0000] {processor.py:153} INFO - Started process (PID=476) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:50:54.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:50:54.104+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:50:54.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:50:54.129+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:50:54.129+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:50:54.137+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:50:54.132+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:50:54.139+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:50:54.176+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.082 seconds
[2024-02-09T14:51:24.298+0000] {processor.py:153} INFO - Started process (PID=504) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:51:24.302+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:51:24.313+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:51:24.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:51:24.353+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:51:24.354+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:51:24.361+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:51:24.356+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:51:24.363+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:51:24.439+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.148 seconds
[2024-02-09T14:51:55.371+0000] {processor.py:153} INFO - Started process (PID=531) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:51:55.392+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:51:55.394+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:51:55.393+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:51:55.449+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:51:55.451+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:51:55.513+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:51:55.492+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:51:55.523+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:51:55.628+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.263 seconds
[2024-02-09T14:52:26.039+0000] {processor.py:153} INFO - Started process (PID=556) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:52:26.081+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:52:26.084+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:52:26.083+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:52:26.156+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:52:26.161+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:52:26.169+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:52:26.163+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:52:26.171+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:52:26.264+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.243 seconds
[2024-02-09T14:52:56.429+0000] {processor.py:153} INFO - Started process (PID=583) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:52:56.431+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:52:56.432+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:52:56.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:52:56.458+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:52:56.459+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:52:56.466+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:52:56.461+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:52:56.468+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:52:56.527+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.105 seconds
[2024-02-09T14:53:26.818+0000] {processor.py:153} INFO - Started process (PID=611) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:53:26.820+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:53:26.821+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:53:26.821+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:53:26.846+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:53:26.847+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:53:26.854+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:53:26.849+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:53:26.855+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:53:26.892+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.080 seconds
[2024-02-09T14:53:57.356+0000] {processor.py:153} INFO - Started process (PID=631) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:53:57.358+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:53:57.359+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:53:57.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:53:57.384+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:53:57.384+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:53:57.391+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:53:57.386+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:53:57.392+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:53:57.422+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.071 seconds
[2024-02-09T14:54:28.178+0000] {processor.py:153} INFO - Started process (PID=661) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:54:28.180+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:54:28.181+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:54:28.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:54:28.201+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:54:28.202+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:54:28.208+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:54:28.204+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:54:28.210+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:54:28.240+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.067 seconds
[2024-02-09T14:54:58.352+0000] {processor.py:153} INFO - Started process (PID=690) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:54:58.354+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:54:58.356+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:54:58.355+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:54:58.384+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:54:58.385+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:54:58.392+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:54:58.387+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:54:58.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:54:58.439+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.095 seconds
[2024-02-09T14:55:28.932+0000] {processor.py:153} INFO - Started process (PID=719) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:55:28.938+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:55:28.941+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:55:28.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:55:28.976+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:55:28.979+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:55:29.002+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:55:28.982+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:55:29.006+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:55:29.081+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.156 seconds
[2024-02-09T14:55:59.237+0000] {processor.py:153} INFO - Started process (PID=746) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:55:59.239+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:55:59.240+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:55:59.240+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:55:59.270+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:55:59.275+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:55:59.286+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:55:59.279+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:55:59.288+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:55:59.336+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.106 seconds
[2024-02-09T14:56:29.689+0000] {processor.py:153} INFO - Started process (PID=775) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:56:29.691+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:56:29.693+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:56:29.692+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:56:29.721+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:56:29.722+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:56:29.730+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:56:29.724+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:56:29.732+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:56:29.775+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.093 seconds
[2024-02-09T14:57:00.252+0000] {processor.py:153} INFO - Started process (PID=804) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:57:00.253+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:57:00.255+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:57:00.254+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:57:00.276+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:57:00.276+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:57:00.285+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:57:00.278+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:57:00.288+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:57:00.357+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.110 seconds
[2024-02-09T14:57:31.183+0000] {processor.py:153} INFO - Started process (PID=832) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:57:31.185+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:57:31.186+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:57:31.186+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:57:31.208+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:57:31.209+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:57:31.215+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:57:31.210+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:57:31.216+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:57:31.243+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.065 seconds
[2024-02-09T14:58:01.468+0000] {processor.py:153} INFO - Started process (PID=861) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:58:01.469+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:58:01.470+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:58:01.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:58:01.488+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:58:01.489+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:58:01.496+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:58:01.491+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:58:01.498+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:58:01.526+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.063 seconds
[2024-02-09T14:58:32.075+0000] {processor.py:153} INFO - Started process (PID=891) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:58:32.078+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:58:32.080+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:58:32.079+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:58:32.108+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:58:32.110+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:58:32.119+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:58:32.112+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:58:32.120+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:58:32.168+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.100 seconds
[2024-02-09T14:59:03.045+0000] {processor.py:153} INFO - Started process (PID=920) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:59:03.046+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:59:03.048+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:59:03.048+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:59:03.081+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:59:03.082+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:59:03.090+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:59:03.084+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:59:03.092+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:59:03.144+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.107 seconds
[2024-02-09T14:59:33.638+0000] {processor.py:153} INFO - Started process (PID=950) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T14:59:33.639+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T14:59:33.640+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:59:33.640+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:59:33.660+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T14:59:33.661+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T14:59:33.667+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:59:33.662+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T14:59:33.669+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T14:59:33.699+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.067 seconds
[2024-02-09T15:00:04.397+0000] {processor.py:153} INFO - Started process (PID=978) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:00:04.398+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:00:04.401+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:00:04.400+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:00:04.431+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:00:04.432+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:00:04.441+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:00:04.435+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:00:04.443+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:00:04.495+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.107 seconds
[2024-02-09T15:00:35.217+0000] {processor.py:153} INFO - Started process (PID=1003) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:00:35.230+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:00:35.233+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:00:35.233+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:00:35.282+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:00:35.290+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:00:35.300+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:00:35.292+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:00:35.302+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:00:35.414+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.223 seconds
[2024-02-09T15:01:05.899+0000] {processor.py:153} INFO - Started process (PID=1032) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:01:05.901+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:01:05.902+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:01:05.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:01:05.920+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:01:05.920+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:01:05.925+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:01:05.922+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:01:05.927+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:01:05.964+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.070 seconds
[2024-02-09T15:01:36.205+0000] {processor.py:153} INFO - Started process (PID=1063) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:01:36.206+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:01:36.208+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:01:36.208+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:01:36.227+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:01:36.228+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:01:36.234+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:01:36.230+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:01:36.235+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:01:36.263+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.064 seconds
[2024-02-09T15:02:06.802+0000] {processor.py:153} INFO - Started process (PID=1091) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:02:06.810+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:02:06.815+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:02:06.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:02:06.841+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:02:06.842+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:02:06.853+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:02:06.847+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:02:06.855+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:02:06.936+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.141 seconds
[2024-02-09T15:02:37.197+0000] {processor.py:153} INFO - Started process (PID=1121) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:02:37.204+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:02:37.206+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:02:37.205+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:02:37.250+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:02:37.251+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:02:37.258+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:02:37.253+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:02:37.260+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:02:37.355+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.165 seconds
[2024-02-09T15:03:07.865+0000] {processor.py:153} INFO - Started process (PID=1150) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:03:07.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:03:07.868+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:03:07.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:03:07.889+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:03:07.890+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:03:07.896+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:03:07.891+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:03:07.898+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:03:07.939+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.082 seconds
[2024-02-09T15:03:38.354+0000] {processor.py:153} INFO - Started process (PID=1181) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:03:38.356+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:03:38.357+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:03:38.357+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:03:38.380+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:03:38.381+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:03:38.388+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:03:38.383+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:03:38.392+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:03:38.434+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.084 seconds
[2024-02-09T15:04:08.864+0000] {processor.py:153} INFO - Started process (PID=1210) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:04:08.866+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:04:08.867+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:04:08.867+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:04:08.886+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:04:08.886+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:04:08.892+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:04:08.888+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:04:08.895+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:04:08.926+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.068 seconds
[2024-02-09T15:04:39.308+0000] {processor.py:153} INFO - Started process (PID=1239) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:04:39.310+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:04:39.323+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:04:39.323+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:04:40.177+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:04:40.189+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:04:40.384+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:04:40.237+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:04:40.559+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:04:40.897+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 1.616 seconds
[2024-02-09T15:05:11.302+0000] {processor.py:153} INFO - Started process (PID=1267) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:05:11.306+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:05:11.308+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:05:11.308+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:05:11.385+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:05:11.386+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:05:11.440+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:05:11.402+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:05:11.443+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:05:11.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.361 seconds
[2024-02-09T15:05:42.087+0000] {processor.py:153} INFO - Started process (PID=1291) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:05:42.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:05:42.110+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:05:42.110+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:05:42.147+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:05:42.164+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:05:42.213+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:05:42.174+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:05:42.233+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:05:42.366+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.289 seconds
[2024-02-09T15:06:12.757+0000] {processor.py:153} INFO - Started process (PID=1311) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:06:12.759+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:06:12.761+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:06:12.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:06:12.783+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:06:12.784+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:06:12.791+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:06:12.786+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:06:12.794+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:06:12.839+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.089 seconds
[2024-02-09T15:06:43.158+0000] {processor.py:153} INFO - Started process (PID=1339) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:06:43.159+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:06:43.160+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:06:43.160+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:06:43.182+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:06:43.184+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:06:43.191+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:06:43.186+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:06:43.192+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:06:43.221+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.069 seconds
[2024-02-09T15:07:13.811+0000] {processor.py:153} INFO - Started process (PID=1368) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:07:13.814+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:07:13.816+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:07:13.815+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:07:13.835+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:07:13.836+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:07:13.842+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:07:13.838+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:07:13.843+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:07:13.871+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.068 seconds
[2024-02-09T15:07:44.530+0000] {processor.py:153} INFO - Started process (PID=1397) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:07:44.532+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:07:44.536+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:07:44.535+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:07:44.574+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:07:44.575+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:07:44.583+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:07:44.577+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:07:44.585+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:07:44.651+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.135 seconds
[2024-02-09T15:08:15.325+0000] {processor.py:153} INFO - Started process (PID=1427) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:08:15.326+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:08:15.328+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:08:15.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:08:15.345+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:08:15.346+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:08:15.353+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:08:15.348+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:08:15.354+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:08:15.385+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.070 seconds
[2024-02-09T15:08:45.936+0000] {processor.py:153} INFO - Started process (PID=1465) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:08:45.956+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:08:45.958+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:08:45.958+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:08:45.985+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:08:45.986+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:08:45.994+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:08:45.988+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:08:45.996+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:08:46.035+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.106 seconds
[2024-02-09T15:09:16.923+0000] {processor.py:153} INFO - Started process (PID=1492) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:09:16.925+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:09:16.927+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:09:16.926+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:09:16.959+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:09:16.960+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:09:16.976+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:09:16.963+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:09:16.978+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:09:17.025+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.115 seconds
[2024-02-09T15:09:47.226+0000] {processor.py:153} INFO - Started process (PID=1520) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:09:47.230+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:09:47.235+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:09:47.234+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:09:47.356+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:09:47.360+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:09:47.410+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:09:47.389+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:09:47.443+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:09:47.682+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.465 seconds
[2024-02-09T15:10:18.485+0000] {processor.py:153} INFO - Started process (PID=1551) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:10:18.487+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:10:18.489+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:10:18.489+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:10:18.514+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:10:18.514+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:10:18.522+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:10:18.517+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:10:18.524+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:10:18.569+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.091 seconds
[2024-02-09T15:10:48.676+0000] {processor.py:153} INFO - Started process (PID=1583) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:10:48.678+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:10:48.680+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:10:48.679+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:10:48.701+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:10:48.702+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:10:48.707+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:10:48.703+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:10:48.709+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:10:48.738+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.068 seconds
[2024-02-09T15:11:19.066+0000] {processor.py:153} INFO - Started process (PID=1609) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:11:19.075+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:11:19.084+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:11:19.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:11:19.180+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:11:19.181+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:11:19.194+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:11:19.186+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:11:19.196+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:11:19.238+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.210 seconds
[2024-02-09T15:11:49.939+0000] {processor.py:153} INFO - Started process (PID=1638) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:11:49.952+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:11:49.957+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:11:49.957+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:11:49.997+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:11:49.998+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:11:50.004+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:11:50.000+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:11:50.030+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:11:50.159+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.234 seconds
[2024-02-09T15:12:20.778+0000] {processor.py:153} INFO - Started process (PID=1668) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:12:20.779+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:12:20.781+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:12:20.781+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:12:20.807+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:12:20.808+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:12:20.815+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:12:20.810+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:12:20.817+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:12:20.854+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.083 seconds
[2024-02-09T15:12:51.356+0000] {processor.py:153} INFO - Started process (PID=1696) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:12:51.367+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:12:51.369+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:12:51.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:12:51.405+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:12:51.416+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:12:51.423+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:12:51.418+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:12:51.425+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:12:51.484+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.139 seconds
[2024-02-09T15:13:21.698+0000] {processor.py:153} INFO - Started process (PID=1724) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:13:21.706+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:13:21.709+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:13:21.708+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:13:21.767+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:13:21.770+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:13:21.780+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:13:21.772+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:13:21.784+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:13:21.927+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.235 seconds
[2024-02-09T15:13:52.720+0000] {processor.py:153} INFO - Started process (PID=1754) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:13:52.725+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:13:52.727+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:13:52.727+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:13:52.790+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:13:52.791+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:13:52.805+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:13:52.799+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:13:52.807+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:13:52.877+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.169 seconds
[2024-02-09T15:14:23.474+0000] {processor.py:153} INFO - Started process (PID=1783) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:14:23.477+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:14:23.478+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:14:23.478+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:14:23.541+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:14:23.543+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:14:23.578+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:14:23.552+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:14:23.591+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:14:23.638+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.180 seconds
[2024-02-09T15:14:58.112+0000] {processor.py:153} INFO - Started process (PID=1812) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:14:58.220+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:14:58.339+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:14:58.335+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:15:01.254+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:15:01.317+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:15:02.088+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:15:01.657+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:15:02.200+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:15:02.388+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 4.294 seconds
[2024-02-09T15:15:33.384+0000] {processor.py:153} INFO - Started process (PID=1841) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:15:33.385+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:15:33.386+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:15:33.386+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:15:33.407+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:15:33.408+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:15:33.414+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:15:33.409+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:15:33.415+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:15:33.444+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.067 seconds
[2024-02-09T15:16:03.789+0000] {processor.py:153} INFO - Started process (PID=1870) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:16:03.791+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:16:03.792+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:16:03.792+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:16:03.819+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:16:03.820+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:16:03.827+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:16:03.822+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:16:03.829+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:16:03.856+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.073 seconds
[2024-02-09T15:16:34.105+0000] {processor.py:153} INFO - Started process (PID=1899) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:16:34.107+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:16:34.109+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:16:34.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:16:34.135+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:16:34.136+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:16:34.144+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:16:34.138+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:16:34.146+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:16:34.178+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.079 seconds
[2024-02-09T15:17:04.957+0000] {processor.py:153} INFO - Started process (PID=1928) to work on /opt/airflow/dags/hw_dag.py
[2024-02-09T15:17:04.971+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/hw_dag.py for tasks to queue
[2024-02-09T15:17:04.974+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:17:04.974+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:17:05.061+0000] {logging_mixin.py:137} INFO - qwqweqweqwe D:/33 module/airflow_hw-main
[2024-02-09T15:17:05.073+0000] {logging_mixin.py:137} INFO - None
[2024-02-09T15:17:05.127+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:17:05.075+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/hw_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/hw_dag.py", line 16, in <module>
    from dags.modules.pipeline import pipeline
ModuleNotFoundError: No module named 'dags'
[2024-02-09T15:17:05.133+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/hw_dag.py
[2024-02-09T15:17:05.222+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/hw_dag.py took 0.273 seconds
