[2024-02-09T14:44:17.095+0000] {processor.py:153} INFO - Started process (PID=90) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:44:17.099+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:44:17.104+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:44:17.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:44:19.837+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:44:19.820+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:44:19.840+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:44:19.876+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 2.796 seconds
[2024-02-09T14:44:50.728+0000] {processor.py:153} INFO - Started process (PID=126) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:44:50.730+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:44:50.732+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:44:50.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:44:51.482+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:44:51.472+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:44:51.485+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:44:51.512+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.791 seconds
[2024-02-09T14:45:22.080+0000] {processor.py:153} INFO - Started process (PID=155) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:45:22.082+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:45:22.083+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:45:22.083+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:45:23.314+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:45:23.286+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:45:23.316+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:45:23.424+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 1.352 seconds
[2024-02-09T14:45:53.660+0000] {processor.py:153} INFO - Started process (PID=187) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:45:53.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:45:53.663+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:45:53.663+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:45:54.319+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:45:54.310+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:45:54.321+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:45:54.353+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.698 seconds
[2024-02-09T14:46:24.819+0000] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:46:24.820+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:46:24.821+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:46:24.821+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:46:25.299+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:46:25.291+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:46:25.301+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:46:25.327+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.514 seconds
[2024-02-09T14:46:55.495+0000] {processor.py:153} INFO - Started process (PID=242) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:46:55.497+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:46:55.499+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:46:55.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:46:56.260+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:46:56.249+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:46:56.263+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:46:56.373+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.885 seconds
[2024-02-09T14:47:26.831+0000] {processor.py:153} INFO - Started process (PID=262) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:47:26.832+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:47:26.834+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:47:26.833+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:47:27.271+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:47:27.263+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:47:27.273+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:47:27.304+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.477 seconds
[2024-02-09T14:47:57.408+0000] {processor.py:153} INFO - Started process (PID=291) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:47:57.410+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:47:57.411+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:47:57.411+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:47:57.904+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:47:57.897+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:47:57.906+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:47:57.932+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.530 seconds
[2024-02-09T14:48:28.450+0000] {processor.py:153} INFO - Started process (PID=333) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:48:28.452+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:48:28.454+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:48:28.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:48:29.024+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:48:29.015+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:48:29.029+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:48:29.062+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.618 seconds
[2024-02-09T14:48:59.880+0000] {processor.py:153} INFO - Started process (PID=362) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:48:59.881+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:48:59.883+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:48:59.883+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:49:00.417+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:49:00.405+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:49:00.420+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:49:00.449+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.574 seconds
[2024-02-09T14:49:30.859+0000] {processor.py:153} INFO - Started process (PID=391) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:49:30.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:49:30.862+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:49:30.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:49:31.295+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:49:31.287+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:49:31.297+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:49:31.327+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.472 seconds
[2024-02-09T14:50:01.580+0000] {processor.py:153} INFO - Started process (PID=420) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:50:01.582+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:50:01.583+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:50:01.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:50:01.944+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:50:01.935+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:50:01.946+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:50:01.974+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.398 seconds
[2024-02-09T14:50:32.896+0000] {processor.py:153} INFO - Started process (PID=449) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:50:32.897+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:50:32.898+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:50:32.898+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:50:33.398+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:50:33.390+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:50:33.400+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:50:33.437+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.545 seconds
[2024-02-09T14:51:04.261+0000] {processor.py:153} INFO - Started process (PID=477) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:51:04.262+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:51:04.263+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:51:04.263+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:51:04.629+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:51:04.622+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:51:04.631+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:51:04.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.399 seconds
[2024-02-09T14:51:35.453+0000] {processor.py:153} INFO - Started process (PID=505) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:51:35.456+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:51:35.459+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:51:35.458+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:51:36.025+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:51:36.018+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:51:36.027+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:51:36.055+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.621 seconds
[2024-02-09T14:52:06.582+0000] {processor.py:153} INFO - Started process (PID=532) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:52:06.583+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:52:06.585+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:52:06.585+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:52:07.123+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:52:07.114+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:52:07.126+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:52:07.162+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.586 seconds
[2024-02-09T14:52:37.508+0000] {processor.py:153} INFO - Started process (PID=560) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:52:37.510+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:52:37.512+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:52:37.511+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:52:38.045+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:52:38.037+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:52:38.047+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:52:38.094+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.592 seconds
[2024-02-09T14:53:08.632+0000] {processor.py:153} INFO - Started process (PID=587) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:53:08.633+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:53:08.635+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:53:08.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:53:09.354+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:53:09.326+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:53:09.367+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:53:09.417+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.790 seconds
[2024-02-09T14:53:40.022+0000] {processor.py:153} INFO - Started process (PID=615) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:53:40.024+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:53:40.028+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:53:40.027+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:53:41.010+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:53:40.992+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:53:41.013+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:53:41.075+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 1.059 seconds
[2024-02-09T14:54:11.608+0000] {processor.py:153} INFO - Started process (PID=644) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:54:11.618+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:54:11.620+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:54:11.620+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:54:12.510+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:54:12.496+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:54:12.518+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:54:12.565+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.963 seconds
[2024-02-09T14:54:43.377+0000] {processor.py:153} INFO - Started process (PID=674) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:54:43.378+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:54:43.380+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:54:43.379+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:54:44.056+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:54:44.045+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:54:44.059+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:54:44.107+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.735 seconds
[2024-02-09T14:55:14.694+0000] {processor.py:153} INFO - Started process (PID=710) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:55:14.700+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:55:14.701+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:55:14.701+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:55:15.847+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:55:15.838+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:55:15.853+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:55:15.895+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 1.210 seconds
[2024-02-09T14:55:46.360+0000] {processor.py:153} INFO - Started process (PID=741) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:55:46.362+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:55:46.364+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:55:46.363+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:55:46.921+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:55:46.907+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:55:46.924+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:55:46.962+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.609 seconds
[2024-02-09T14:56:17.532+0000] {processor.py:153} INFO - Started process (PID=761) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:56:17.534+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:56:17.535+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:56:17.535+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:56:18.094+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:56:18.085+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:56:18.096+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:56:18.126+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.607 seconds
[2024-02-09T14:56:48.615+0000] {processor.py:153} INFO - Started process (PID=790) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:56:48.616+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:56:48.617+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:56:48.617+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:56:49.090+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:56:49.082+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:56:49.093+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:56:49.120+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.510 seconds
[2024-02-09T14:57:19.717+0000] {processor.py:153} INFO - Started process (PID=818) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:57:19.718+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:57:19.719+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:57:19.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:57:20.073+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:57:20.064+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:57:20.076+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:57:20.100+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.388 seconds
[2024-02-09T14:57:50.580+0000] {processor.py:153} INFO - Started process (PID=847) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:57:50.582+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:57:50.583+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:57:50.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:57:51.183+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:57:51.174+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:57:51.185+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:57:51.219+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.643 seconds
[2024-02-09T14:58:21.707+0000] {processor.py:153} INFO - Started process (PID=876) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:58:21.708+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:58:21.709+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:58:21.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:58:22.124+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:58:22.116+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:58:22.126+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:58:22.153+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.451 seconds
[2024-02-09T14:58:52.567+0000] {processor.py:153} INFO - Started process (PID=906) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:58:52.568+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:58:52.570+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:58:52.570+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:58:52.932+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:58:52.923+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:58:52.934+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:58:52.958+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.398 seconds
[2024-02-09T14:59:23.264+0000] {processor.py:153} INFO - Started process (PID=936) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:59:23.266+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:59:23.267+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:59:23.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:59:23.723+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:59:23.714+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:59:23.726+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:59:23.758+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.500 seconds
[2024-02-09T14:59:54.130+0000] {processor.py:153} INFO - Started process (PID=964) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T14:59:54.132+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T14:59:54.133+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:59:54.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:59:54.513+0000] {logging_mixin.py:137} INFO - [2024-02-09T14:59:54.505+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T14:59:54.514+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T14:59:54.538+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.415 seconds
[2024-02-09T15:00:24.878+0000] {processor.py:153} INFO - Started process (PID=992) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:00:24.881+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:00:24.884+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:00:24.883+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:00:25.265+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:00:25.257+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:00:25.266+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:00:25.295+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.427 seconds
[2024-02-09T15:00:55.497+0000] {processor.py:153} INFO - Started process (PID=1021) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:00:55.498+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:00:55.500+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:00:55.500+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:00:56.035+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:00:56.025+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:00:56.038+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:00:56.088+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.598 seconds
[2024-02-09T15:01:26.271+0000] {processor.py:153} INFO - Started process (PID=1049) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:01:26.273+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:01:26.275+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:01:26.275+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:01:26.911+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:01:26.901+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:01:26.913+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:01:26.953+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.692 seconds
[2024-02-09T15:01:57.098+0000] {processor.py:153} INFO - Started process (PID=1078) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:01:57.105+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:01:57.109+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:01:57.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:01:57.719+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:01:57.711+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:01:57.721+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:01:57.753+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.662 seconds
[2024-02-09T15:02:28.345+0000] {processor.py:153} INFO - Started process (PID=1107) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:02:28.348+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:02:28.350+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:02:28.350+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:02:28.992+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:02:28.984+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:02:28.994+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:02:29.025+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.687 seconds
[2024-02-09T15:02:59.463+0000] {processor.py:153} INFO - Started process (PID=1136) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:02:59.465+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:02:59.467+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:02:59.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:02:59.967+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:02:59.959+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:02:59.970+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:02:59.999+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.541 seconds
[2024-02-09T15:03:30.187+0000] {processor.py:153} INFO - Started process (PID=1174) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:03:30.188+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:03:30.190+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:03:30.190+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:03:30.780+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:03:30.769+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:03:30.783+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:03:30.825+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.647 seconds
[2024-02-09T15:04:01.648+0000] {processor.py:153} INFO - Started process (PID=1206) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:04:01.650+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:04:01.652+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:04:01.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:04:02.177+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:04:02.167+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:04:02.179+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:04:02.218+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.580 seconds
[2024-02-09T15:04:32.349+0000] {processor.py:153} INFO - Started process (PID=1235) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:04:32.351+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:04:32.355+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:04:32.355+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:04:33.208+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:04:33.189+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:04:33.219+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:04:33.305+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.967 seconds
[2024-02-09T15:05:03.926+0000] {processor.py:153} INFO - Started process (PID=1260) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:05:03.929+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:05:03.935+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:05:03.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:05:06.268+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:05:06.067+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:05:06.271+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:05:06.385+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 2.475 seconds
[2024-02-09T15:05:37.008+0000] {processor.py:153} INFO - Started process (PID=1280) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:05:37.010+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:05:37.013+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:05:37.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:05:37.842+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:05:37.831+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:05:37.848+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:05:37.883+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.889 seconds
[2024-02-09T15:06:08.660+0000] {processor.py:153} INFO - Started process (PID=1309) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:06:08.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:06:08.663+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:06:08.663+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:06:09.250+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:06:09.242+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:06:09.253+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:06:09.289+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.638 seconds
[2024-02-09T15:06:39.522+0000] {processor.py:153} INFO - Started process (PID=1337) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:06:39.523+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:06:39.525+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:06:39.525+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:06:39.992+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:06:39.984+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:06:39.994+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:06:40.018+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.502 seconds
[2024-02-09T15:07:10.258+0000] {processor.py:153} INFO - Started process (PID=1366) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:07:10.260+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:07:10.261+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:07:10.261+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:07:10.790+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:07:10.782+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:07:10.792+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:07:10.825+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.574 seconds
[2024-02-09T15:07:40.967+0000] {processor.py:153} INFO - Started process (PID=1395) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:07:40.969+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:07:40.971+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:07:40.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:07:41.593+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:07:41.584+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:07:41.595+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:07:41.631+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.669 seconds
[2024-02-09T15:08:12.057+0000] {processor.py:153} INFO - Started process (PID=1425) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:08:12.059+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:08:12.061+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:08:12.061+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:08:12.426+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:08:12.416+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:08:12.429+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:08:12.457+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.406 seconds
[2024-02-09T15:08:43.028+0000] {processor.py:153} INFO - Started process (PID=1455) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:08:43.033+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:08:43.038+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:08:43.037+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:08:43.826+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:08:43.819+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:08:43.829+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:08:43.859+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.839 seconds
[2024-02-09T15:09:14.269+0000] {processor.py:153} INFO - Started process (PID=1484) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:09:14.273+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:09:14.277+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:09:14.276+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:09:14.958+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:09:14.948+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:09:14.960+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:09:14.986+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.728 seconds
[2024-02-09T15:09:45.281+0000] {processor.py:153} INFO - Started process (PID=1511) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:09:45.284+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:09:45.287+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:09:45.287+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:09:45.977+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:09:45.966+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:09:45.980+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:09:46.014+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.744 seconds
[2024-02-09T15:10:16.220+0000] {processor.py:153} INFO - Started process (PID=1540) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:10:16.222+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:10:16.225+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:10:16.224+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:10:16.604+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:10:16.596+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:10:16.606+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:10:16.631+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.423 seconds
[2024-02-09T15:10:47.367+0000] {processor.py:153} INFO - Started process (PID=1578) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:10:47.368+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:10:47.370+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:10:47.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:10:47.794+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:10:47.785+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:10:47.796+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:10:47.823+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.461 seconds
[2024-02-09T15:11:18.025+0000] {processor.py:153} INFO - Started process (PID=1607) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:11:18.027+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:11:18.029+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:11:18.028+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:11:18.809+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:11:18.793+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:11:18.812+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:11:18.860+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.848 seconds
[2024-02-09T15:11:49.266+0000] {processor.py:153} INFO - Started process (PID=1636) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:11:49.268+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:11:49.270+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:11:49.269+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:11:50.220+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:11:50.191+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:11:50.225+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:11:50.275+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 1.020 seconds
[2024-02-09T15:12:20.795+0000] {processor.py:153} INFO - Started process (PID=1669) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:12:20.796+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:12:20.798+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:12:20.797+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:12:21.246+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:12:21.238+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:12:21.248+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:12:21.274+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.485 seconds
[2024-02-09T15:12:51.561+0000] {processor.py:153} INFO - Started process (PID=1697) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:12:51.573+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:12:51.575+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:12:51.574+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:12:52.160+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:12:52.150+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:12:52.163+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:12:52.239+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.685 seconds
[2024-02-09T15:13:23.037+0000] {processor.py:153} INFO - Started process (PID=1725) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:13:23.062+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:13:23.081+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:13:23.079+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:13:24.060+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:13:24.050+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:13:24.063+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:13:24.120+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 1.090 seconds
[2024-02-09T15:13:54.906+0000] {processor.py:153} INFO - Started process (PID=1755) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:13:54.917+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:13:54.919+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:13:54.918+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:13:55.786+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:13:55.776+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:13:55.789+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:13:55.858+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.971 seconds
[2024-02-09T15:14:26.591+0000] {processor.py:153} INFO - Started process (PID=1784) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:14:26.592+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:14:26.594+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:14:26.594+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:14:27.055+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:14:27.048+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:14:27.058+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:14:27.094+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.510 seconds
[2024-02-09T15:15:00.901+0000] {processor.py:153} INFO - Started process (PID=1813) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:15:00.917+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:15:00.951+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:15:00.951+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:15:09.069+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:15:08.894+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:15:09.215+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:15:09.684+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 8.857 seconds
[2024-02-09T15:15:40.533+0000] {processor.py:153} INFO - Started process (PID=1851) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:15:40.535+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:15:40.537+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:15:40.537+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:15:41.235+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:15:41.228+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:15:41.236+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:15:41.263+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.738 seconds
[2024-02-09T15:16:11.624+0000] {processor.py:153} INFO - Started process (PID=1881) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:16:11.629+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:16:11.638+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:16:11.634+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:16:12.764+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:16:12.757+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:16:12.767+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:16:12.798+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 1.221 seconds
[2024-02-09T15:16:43.341+0000] {processor.py:153} INFO - Started process (PID=1912) to work on /opt/airflow/dags/modules/predict.py
[2024-02-09T15:16:43.343+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/modules/predict.py for tasks to queue
[2024-02-09T15:16:43.346+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:16:43.345+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:16:43.826+0000] {logging_mixin.py:137} INFO - [2024-02-09T15:16:43.815+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/modules/predict.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/predict.py", line 10, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
[2024-02-09T15:16:43.828+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/predict.py
[2024-02-09T15:16:43.857+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/modules/predict.py took 0.523 seconds
